# This is a basic workflow to help you get started with Actions

name: books-grid-update

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Creating new book grid from Books.json
        run: python scripts/book_grid_generator.py > Books.md

      - name: commit files
        run: |
          git config --local user.email "m.erfan.gh@gmail.com"
          git config --local user.name "mirerfangheibi"
          git add -A
          git commit -m "Updated Books.md" -a
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
